name: hanzishu
description: Hanzishu project using new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: "^0.4.0"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  flutter_tts: ^2.1.0

  json_annotation: ^3.0.0

  flutter_launcher_icons: ^0.8.1

  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^3.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
   android: "launcher_icon"
   ios: true
   image_path: "assets/core/logo.jpg"
   image_path_android: "assets/core/logoandroid.png"
   adaptive_icon_background: "#ffffff"
#   adaptive_icon_foreground: "assets/christmas.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/components/LC00.png
     - assets/components/LC11.png
     - assets/components/LC12.png
     - assets/components/LC13.png
     - assets/components/LC14.png
     - assets/components/LC15.png
     - assets/components/LC21.png
     - assets/components/LC22.png
     - assets/components/LC23.png
     - assets/components/LC24.png
     - assets/components/LC25.png
     - assets/components/LC31.png
     - assets/components/LC32.png
     - assets/components/LC33.png
     - assets/components/LC34.png
     - assets/components/LC35.png
     - assets/components/LC41.png
     - assets/components/LC42.png
     - assets/components/LC43.png
     - assets/components/LC44.png
     - assets/components/LC51.png
     - assets/components/LC52.png
     - assets/components/LC53.png
     - assets/components/LC54.png
     - assets/components/LC55.png
     - assets/components/LC61.png
     - assets/components/LC62.png
     - assets/core/breakout.png
     - assets/core/characterdrill.png
     - assets/core/characterlist.png
     - assets/core/characterreview.png
     - assets/core/completedicon.png
     - assets/core/conversations.png
     - assets/core/dictionaryicon0.png
     - assets/core/dictionaryicon1.png
     - assets/core/glossary.png
     - assets/core/itemicon.png
     - assets/core/lessonsicon0.png
     - assets/core/lessonsicon1.png
     - assets/core/logo.jpg
     - assets/core/logoandroid.png
     - assets/core/meicon0.png
     - assets/core/meicon1.png
     - assets/core/settings.png
     - assets/core/typing.png
     - assets/core/typingicon0.png
     - assets/core/typingicon1.png
     - assets/core/quiz.png
     - assets/core/quizresults.png
     - assets/lessons/L1.png
     - assets/lessons/L2.png
     - assets/lessons/L3.png
     - assets/lessons/L4.png
     - assets/lessons/L5.png
     - assets/lessons/L6.png
     - assets/lessons/L7.png
     - assets/lessons/L8.png
     - assets/lessons/L9.png
     - assets/lessons/L10.png
     - assets/lessons/L11.png
     - assets/lessons/L12.png
     - assets/lessons/L13.png
     - assets/lessons/L14.png
     - assets/lessons/L15.png
     - assets/lessons/L16.png
     - assets/lessons/L17.png
     - assets/lessons/L18.png
     - assets/lessons/L19.png
     - assets/lessons/L20.png
     - assets/lessons/L21.png
     - assets/lessons/L22.png
     - assets/lessons/L23.png
     - assets/lessons/L24.png
     - assets/lessons/L25.png
     - assets/lessons/L26.png
     - assets/lessons/L27.png
     - assets/lessons/L28.png
     - assets/lessons/L29.png
     - assets/lessons/L30.png
     - assets/lessons/L31.png
     - assets/lessons/L32.png
     - assets/lessons/L33.png
     - assets/lessons/L34.png
     - assets/lessons/L35.png
     - assets/lessons/L36.png
     - assets/lessons/L37.png
     - assets/lessons/L38.png
     - assets/lessons/L39.png
     - assets/lessons/L40.png
     - assets/lessons/L41.png
     - assets/lessons/L42.png
     - assets/lessons/L43.png
     - assets/lessons/L44.png
     - assets/lessons/L45.png
     - assets/lessons/L46.png
     - assets/lessons/L47.png
     - assets/lessons/L48.png
     - assets/lessons/L49.png
     - assets/lessons/L50.png
     - assets/lessons/L51.png
     - assets/lessons/L52.png
     - assets/lessons/L53.png
     - assets/lessons/L54.png
     - assets/lessons/L55.png
     - assets/lessons/L56.png
     - assets/lessons/L57.png
     - assets/lessons/L58.png
     - assets/lessons/L59.png
     - assets/lessons/L60.png
     - assets/letters/L11.png
     - assets/letters/L12.png
     - assets/letters/L13.png
     - assets/letters/L14.png
     - assets/letters/L15.png
     - assets/letters/L21.png
     - assets/letters/L22.png
     - assets/letters/L23.png
     - assets/letters/L24.png
     - assets/letters/L25.png
     - assets/letters/L31.png
     - assets/letters/L32.png
     - assets/letters/L33.png
     - assets/letters/L34.png
     - assets/letters/L35.png
     - assets/letters/L41.png
     - assets/letters/L42.png
     - assets/letters/L43.png
     - assets/letters/L44.png
     - assets/letters/L51.png
     - assets/letters/L52.png
     - assets/letters/L53.png
     - assets/letters/L54.png
     - assets/letters/L55.png
     - assets/letters/L61.png
     - assets/letters/L62.png
     - assets/letters/LG1.png
     - assets/letters/LG2.png
     - assets/letters/LG3.png
     - assets/letters/LG4.png
     - assets/letters/LG5.png
     - assets/letters/LG6.png
     - assets/typing/C00.png
     - assets/typing/C11.png
     - assets/typing/C12.png
     - assets/typing/C13.png
     - assets/typing/C14.png
     - assets/typing/C15.png
     - assets/typing/C21.png
     - assets/typing/C22.png
     - assets/typing/C23.png
     - assets/typing/C24.png
     - assets/typing/C25.png
     - assets/typing/C31.png
     - assets/typing/C32.png
     - assets/typing/C33.png
     - assets/typing/C34.png
     - assets/typing/C35.png
     - assets/typing/C41.png
     - assets/typing/C42.png
     - assets/typing/C43.png
     - assets/typing/C44.png
     - assets/typing/C51.png
     - assets/typing/C52.png
     - assets/typing/C53.png
     - assets/typing/C54.png
     - assets/typing/C61.png
     - assets/typing/C62.png
     - assets/typing/E11.png
     - assets/typing/E12.png
     - assets/typing/E13.png
     - assets/typing/E14.png
     - assets/typing/E15.png
     - assets/typing/E21.png
     - assets/typing/E22.png
     - assets/typing/E23.png
     - assets/typing/E24.png
     - assets/typing/E25.png
     - assets/typing/E31.png
     - assets/typing/E32.png
     - assets/typing/E33.png
     - assets/typing/E34.png
     - assets/typing/E35.png
     - assets/typing/E41.png
     - assets/typing/E42.png
     - assets/typing/E43.png
     - assets/typing/E44.png
     - assets/typing/E51.png
     - assets/typing/E52.png
     - assets/typing/E53.png
     - assets/typing/E54.png
     - assets/typing/E61.png
     - assets/typing/E62.png
     - assets/typing/N11.png
     - assets/typing/N12.png
     - assets/typing/N14.png
     - assets/typing/N15.png
     - assets/typing/N21.png
     - assets/typing/N22.png
     - assets/typing/N23.png
     - assets/typing/N24.png
     - assets/typing/N25.png
     - assets/typing/N31.png
     - assets/typing/N32.png
     - assets/typing/N33.png
     - assets/typing/N34.png
     - assets/typing/N35.png
     - assets/typing/N41.png
     - assets/typing/N42.png
     - assets/typing/N43.png
     - assets/typing/N44.png
     - assets/typing/N51.png
     - assets/typing/N52.png
     - assets/typing/N53.png
     - assets/typing/N54.png
     - assets/typing/N61.png
     - assets/typing/N62.png
     - assets/typing/P11.png
     - assets/typing/P14.png
     - assets/typing/P15.png
     - assets/typing/P22.png
     - assets/typing/P23.png
     - assets/typing/P24.png
     - assets/typing/P25.png
     - assets/typing/P32.png
     - assets/typing/P33.png
     - assets/typing/P34.png
     - assets/typing/P35.png
     - assets/typing/P41.png
     - assets/typing/P42.png
     - assets/typing/P43.png
     - assets/typing/P44.png
     - assets/typing/P51.png
     - assets/typing/P52.png
     - assets/typing/P53.png
     - assets/typing/P54.png
     - assets/typing/P61.png
     - assets/typing/P62.png
     - assets/typing/Q11.png
     - assets/typing/Q12.png
     - assets/typing/Q14.png
     - assets/typing/Q15.png
     - assets/typing/Q23.png
     - assets/typing/Q24.png
     - assets/typing/Q25.png
     - assets/typing/Q31.png
     - assets/typing/Q32.png
     - assets/typing/Q33.png
     - assets/typing/Q34.png
     - assets/typing/Q41.png
     - assets/typing/Q44.png
     - assets/typing/Q51.png
     - assets/typing/Q52.png
     - assets/typing/Q54.png
     - assets/typing/Q61.png
     - assets/typing/Q62.png
     - assets/typing/EF11.png
     - assets/typing/EF12.png
     - assets/typing/EF13.png
     - assets/typing/EF14.png
     - assets/typing/EF15.png
     - assets/typing/EF21.png
     - assets/typing/EF22.png
     - assets/typing/EF23.png
     - assets/typing/EF24.png
     - assets/typing/EF25.png
     - assets/typing/EF31.png
     - assets/typing/EF32.png
     - assets/typing/EF33.png
     - assets/typing/EF34.png
     - assets/typing/EF35.png
     - assets/typing/EF41.png
     - assets/typing/EF42.png
     - assets/typing/EF43.png
     - assets/typing/EF44.png
     - assets/typing/EF51.png
     - assets/typing/EF52.png
     - assets/typing/EF53.png
     - assets/typing/EF54.png
     - assets/typing/EF61.png
     - assets/typing/EF62.png
     - assets/typing/EF24Sample.png
     - assets/typing/EF33Sample.png
     - assets/typing/G1.png
     - assets/typing/G2.png
     - assets/typing/G3.png
     - assets/typing/G4.png
     - assets/typing/G5.png
     - assets/typing/G6.png
     - assets/typing/GG1.png
     - assets/typing/GG2.png
     - assets/typing/GG5.png
     - assets/typing/GG6.png
     - assets/typing/GN1.png
     - assets/typing/GN2.png
     - assets/typing/GN3.png
     - assets/typing/GN4.png
     - assets/typing/GN5.png
     - assets/typing/GN6.png
     - assets/typing/EF33.png
     - assets/typing/FullComponents.png
     - assets/typing/Strokes.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
